export type Word = {
  german: string;
  mongolian: string[]; 
};

export const words: Word[] = [
  { german: "anfangen", mongolian: ["Эхлэх"] },
  { german: "arbeiten", mongolian: ["Ажиллах"] },
  { german: "beginnen", mongolian: ["Эхлэх"] },
  { german: "brauchen", mongolian: ["Хэрэгтэй"] },
  { german: "denken", mongolian: ["Бодох"] },
  { german: "dürfen", mongolian: ["Зөвшөөрөх"] },
  { german: "entscheiden", mongolian: ["Шийдэх"] },
  { german: "vergessen", mongolian: ["Мартах"] },
  { german: "erklären", mongolian: ["Тайлбарлах"] },
  { german: "Bescheid sagen", mongolian: ["Мэдэгдэх"] },
  { german: "das Verhalten", mongolian: ["Зан байдал"] },
  { german: "der Unterschied", mongolian: ["Ялгаа"] },
  { german: "die Teilzeitarbeit", mongolian: ["Хагас цагийн ажил"] },
  { german: "die Verantwortung", mongolian: ["Хариуцлага"] },
  { german: "das Gehalt", mongolian: ["Цалин"] },
  { german: "die bewerbung", mongolian: ["Өргөдөл"] },
  { german: "der Streit", mongolian: ["Маргаан"] },
  { german: "das Klima", mongolian: ["Цаг агаар"] },
  { german: "recyceln", mongolian: ["Дахин боловсруулах"] },
  { german: "sparen", mongolian: ["Хэмнэх"] },
  { german: "verschwenden", mongolian: ["Үрэн таран хийх"] },
  { german: "der Strom", mongolian: ["Цахилгаан"] },
  { german: "zusammenfassend", mongolian: ["Дүгнэж хэлэхэд"] },
  { german: "die Gewohnheit", mongolian: ["Дадал"] },
  { german: "sich gewöhnen an", mongolian: ["Дасах"] },
  { german: "selten", mongolian: ["Ховор"] },
  { german: "Fach", mongolian: ["Хичээл"] },
  { german: "bestehen", mongolian: ["Тэнцэх"] },
  { german: "durchfallen", mongolian: ["Унах"] },
  { german: "üben", mongolian: ["Дасгал хийх"] },
  { german: "die Note", mongolian: ["Дүн"] },
  { german: "das Ergebnis", mongolian: ["Үр дүн"] },
  { german: "stolz", mongolian: ["Бахархах"] },
  { german: "wütend", mongolian: ["Ууртай"] },
  { german: "Angst haben vor", mongolian: ["Айх"] },
  { german: "zufrieden", mongolian: ["Сэтгэл хангалуун"] },
  { german: "Gesellschaft", mongolian: ["Нийгэм"] },
  { german: "die Freiheit", mongolian: ["Эрх чөлөө"] },
  { german: "das Recht", mongolian: ["Эрх"] },
  { german: "die Pflicht", mongolian: ["Үүрэг"] },
  { german: "die Gleichheit", mongolian: ["Тэгш байдал"] },
  { german: "erleben", mongolian: ["Туршлага"] },
  { german: "fertig", mongolian: ["Дуусгасан"] },
  { german: "diskutieren", mongolian: ["Хэлэлцэх"] },
  { german: "realistisch", mongolian: ["Бодитой"] },
  { german: "fließend", mongolian: ["Чөлөөтэй"] },
  { german: "insofern", mongolian: ["Тийм учраас"] },
  { german: "infolgedessen", mongolian: ["Үүний үр дүнд"] },
  { german: "die Voraussetzung", mongolian: ["Урьдчилсан нөхцөл"] },
  { german: "erledigen", mongolian: ["Гүйцэтгэх"] },
  { german: "fördern", mongolian: ["Дэмжих"] },
  { german: "häufig", mongolian: ["Тогтмол"] },
  { german: "die Bedingung", mongolian: ["Нөхцөл"] },
  { german: "jedenfalls", mongolian: ["Ямар ч тохиолдолд"] },
  { german: "freiwillig", mongolian: ["Сайн дураар"] },
  { german: "notwendig", mongolian: ["Шаардлагатай"] },
  { german: "gelten", mongolian: ["Хамаарах"] },
  { german: "die unterstützung", mongolian: ["Дэмжлэг"] },
  { german: "die fähigkeit", mongolian: ["Чадвар"] },
  { german: "offen", mongolian: ["Нээлттэй"] },
  { german: "inhaltsreich", mongolian: ["Агуулга баялаг"] },
  { german: "erwarten", mongolian: ["Хүлээх"] },
  { german: "behaupten", mongolian: ["Батлах"] },
  { german: "die Situation", mongolian: ["Нөхцөл байдал"] },
  { german: "die Handlung", mongolian: ["Үйл ажиллагаа"] },
  { german: "klagen", mongolian: ["Гомдоллох"] },
  { german: "gelungen", mongolian: ["Амжилттай болсон"] },
  { german: "die Empfehlung", mongolian: ["Зөвлөмж"] },
];